version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_db:/var/lib/redis:delegated
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_db:
