-- AlterTable
ALTER TABLE `Contract` MODIFY `chain` ENUM('LOCAL', 'ETHEREUM', 'GOERLI', 'MATIC', 'MATICMUMBAI', 'ARBITRUM', 'ARBITRUMNOVA', 'ARBITRUMGOERLI', 'BINANCE', 'BINANCETESTNET', 'FANTOM', 'FANTOMTESTNET', 'MOONBEAM', 'MOONBEAMTESTNET', 'THUNDERCORE', 'THUNDERCORETESTNET', 'AVALANCHE', 'AVALANCHEFUJI') NOT NULL;
